/** Generated by scripts/generate-packet-aliases.mts — do not edit by hand. */
export const aliasesByType = {
  /** var_9413 handler method_6486 */
  16: "keepAlive",
  /** var_2152 */
  17: "toExplore_var_2152",
  /** var_4975 */
  18: "toExplore_var_4975",
  /** PKTTYPE_UNUSED_19 */
  19: "unused19",
  /** var_14901 */
  20: "loginRequest",
  /** var_1802 */
  30: "clientVersion",
  /** var_656 */
  31: "toExplore_var_656",
  /** var_11935 */
  32: "toExplore_var_11935",
  /** var_5874 */
  33: "createCustomRoom",
  /** var_14338 */
  34: "toExplore_var_14338",
  /** var_2721 */
  35: "toExplore_var_2721",
  /** var_12536 */
  36: "toExplore_var_12536",
  /** var_4048 */
  37: "updateSettings",
  /** var_10500 */
  38: "joinCustomRoom",
  /** var_8547 */
  39: "toExplore_var_8547",
  /** var_6105 */
  40: "toExplore_var_6105",
  /** var_5600 */
  41: "legendPick",
  /** var_2612 */
  42: "toExplore_var_2612",
  /** var_14518 */
  43: "lockReady",
  /** var_3770 */
  44: "addBot",
  /** var_1890 */
  45: "toExplore_var_1890",
  /** var_8641 */
  46: "toExplore_var_8641",
  /** var_12109 */
  47: "lobbyTabPing",
  /** var_6739 */
  48: "toExplore_var_6739",
  /** var_4493 */
  49: "toExplore_var_4493",
  /** var_14500 */
  50: "toExplore_var_14500",
  /** var_8472 */
  51: "toExplore_var_8472",
  /** var_7713 */
  52: "toExplore_var_7713",
  /** var_6644 */
  53: "toExplore_var_6644",
  /** var_6612 */
  54: "toExplore_var_6612",
  /** var_6923 */
  55: "startMatch",
  /** var_4552 */
  56: "toExplore_var_4552",
  /** var_2472 */
  57: "toExplore_var_2472",
  /** var_13087 */
  58: "toExplore_var_13087",
  /** var_2960 */
  59: "toExplore_var_2960",
  /** var_14237 */
  60: "toExplore_var_14237",
  /** var_7820 */
  61: "toExplore_var_7820",
  /** var_6430 */
  62: "toExplore_var_6430",
  /** var_14657 */
  63: "toExplore_var_14657",
  /** var_11998 */
  64: "toExplore_var_11998",
  /** var_12894 */
  65: "toExplore_var_12894",
  /** var_14106 */
  66: "toExplore_var_14106",
  /** var_6936 */
  67: "toExplore_var_6936",
  /** var_11911 */
  68: "toExplore_var_11911",
  /** var_4637 */
  69: "toExplore_var_4637",
  /** var_9600 */
  70: "steamOverlayPing",
  /** PKTTYPE_UNUSED_71 */
  71: "unused71",
  /** var_4274 */
  72: "toExplore_var_4274",
  /** var_13278 */
  73: "toExplore_var_13278",
  /** var_15248 */
  74: "toExplore_var_15248",
  /** var_7932 */
  75: "toExplore_var_7932",
  /** var_7476 */
  76: "toExplore_var_7476",
  /** var_2855 */
  77: "toExplore_var_2855",
  /** var_1175 */
  78: "toExplore_var_1175",
  /** var_8778 */
  79: "toExplore_var_8778",
  /** var_12670 */
  80: "localJoin",
  /** var_12822 */
  81: "toExplore_var_12822",
  /** var_3453 */
  82: "toExplore_var_3453",
  /** var_2844 */
  83: "toExplore_var_2844",
  /** var_3586 */
  84: "toExplore_var_3586",
  /** var_5593 */
  85: "toExplore_var_5593",
  /** PKTTYPE_UNUSED_85 */
  86: "unused_85",
  /** var_11909 */
  87: "toExplore_var_11909",
  /** var_2045 */
  88: "loginRequestAlt",
  /** var_5450 */
  89: "toExplore_var_5450",
  /** var_6042 */
  90: "toExplore_var_6042",
  /** var_4606 */
  91: "toExplore_var_4606",
  /** var_818 */
  92: "toExplore_var_818",
  /** var_12767 */
  93: "toExplore_var_12767",
  /** var_13434 */
  94: "toExplore_var_13434",
  /** var_5681 */
  95: "toExplore_var_5681",
  /** var_11056 */
  96: "toExplore_var_11056",
  /** var_13706 */
  97: "toExplore_var_13706",
  /** var_7417 */
  98: "toExplore_var_7417",
  /** var_7061 */
  99: "toExplore_var_7061",
  /** var_2070 */
  100: "toExplore_var_2070",
  /** var_525 */
  101: "toExplore_var_525",
  /** var_2448 */
  102: "toExplore_var_2448",
  /** var_15153 */
  103: "toExplore_var_15153",
  /** var_2093 */
  104: "toExplore_var_2093",
  /** var_15001 */
  105: "toExplore_var_15001",
  /** var_375 */
  106: "toExplore_var_375",
  /** var_13059 */
  107: "toExplore_var_13059",
  /** var_7337 */
  108: "toExplore_var_7337",
  /** var_5439 */
  109: "toExplore_var_5439",
  /** var_13613 */
  110: "toExplore_var_13613",
  /** var_1490 */
  111: "toExplore_var_1490",
  /** var_12851 */
  112: "toExplore_var_12851",
  /** var_1032 */
  113: "toExplore_var_1032",
  /** var_13689 */
  114: "toExplore_var_13689",
  /** var_7835 */
  115: "toExplore_var_7835",
  /** var_899 */
  116: "toExplore_var_899",
  /** var_11649 */
  117: "toExplore_var_11649",
  /** var_9078 */
  118: "toExplore_var_9078",
  /** var_13931 */
  119: "toExplore_var_13931",
  /** var_8984 */
  120: "toExplore_var_8984",
  /** var_8575 */
  121: "toExplore_var_8575",
  /** var_14155 */
  122: "toExplore_var_14155",
  /** var_7888 */
  123: "toExplore_var_7888",
  /** var_2742 */
  124: "toExplore_var_2742",
  /** var_3687 */
  125: "toExplore_var_3687",
  /** var_11129 */
  126: "toExplore_var_11129",
  /** var_12868 */
  127: "toExplore_var_12868",
  /** var_6489 */
  128: "toExplore_var_6489",
  /** var_10341 */
  129: "toExplore_var_10341",
  /** var_12247 */
  130: "toExplore_var_12247",
  /** var_3452 */
  131: "toExplore_var_3452",
  /** var_6827 */
  132: "toExplore_var_6827",
  /** var_5510 */
  133: "toExplore_var_5510",
  /** var_3226 */
  134: "toExplore_var_3226",
  /** var_9378 */
  135: "toExplore_var_9378",
  /** var_11807 */
  136: "toExplore_var_11807",
  /** var_7089 */
  137: "toExplore_var_7089",
  /** var_3845 */
  138: "toExplore_var_3845",
  /** var_3864 */
  139: "toExplore_var_3864",
  /** var_11099 */
  140: "toExplore_var_11099",
  /** var_5761 */
  141: "toExplore_var_5761",
  /** var_1364 */
  142: "toExplore_var_1364",
  /** var_14720 */
  143: "toExplore_var_14720",
  /** var_7424 */
  144: "toExplore_var_7424",
  /** var_11028 */
  145: "toExplore_var_11028",
  /** var_15185 */
  146: "toExplore_var_15185",
  /** var_1686 */
  147: "toExplore_var_1686",
  /** var_10708 */
  148: "toExplore_var_10708",
  /** var_15296 */
  149: "toExplore_var_15296",
  /** var_6181 */
  150: "toExplore_var_6181",
  /** var_13411 */
  151: "toExplore_var_13411",
  /** var_1295 */
  152: "toExplore_var_1295",
  /** var_9470 */
  153: "toExplore_var_9470",
  /** var_9578 */
  154: "toExplore_var_9578",
  /** var_5619 */
  155: "toExplore_var_5619",
  /** var_1439 */
  156: "toExplore_var_1439",
  /** var_9047 */
  157: "toExplore_var_9047",
  /** var_8064 */
  158: "toExplore_var_8064",
  /** var_1205 */
  159: "toExplore_var_1205",
  /** var_3841 */
  160: "toExplore_var_3841",
  /** var_8527 */
  161: "toExplore_var_8527",
  /** var_5839 */
  162: "toExplore_var_5839",
  /** var_703 */
  163: "toExplore_var_703",
  /** var_828 */
  164: "toExplore_var_828",
  /** var_13331 */
  165: "toExplore_var_13331",
  /** var_14869 */
  166: "toExplore_var_14869",
  /** var_2753 */
  167: "toExplore_var_2753",
  /** var_14146 */
  168: "toExplore_var_14146",
  /** var_2495 */
  169: "toExplore_var_2495",
  /** var_5875 */
  170: "toExplore_var_5875",
  /** var_11674 */
  171: "toExplore_var_11674",
  /** var_13855 */
  172: "toExplore_var_13855",
  /** var_4588 */
  173: "toExplore_var_4588",
  /** var_8734 */
  174: "toExplore_var_8734",
  /** var_4269 */
  175: "toExplore_var_4269",
  /** var_3331 */
  176: "toExplore_var_3331",
  /** var_9692 */
  177: "toExplore_var_9692",
  /** var_3163 */
  178: "protocolHello",
  /** var_8497 */
  179: "toExplore_var_8497",
  /** var_2890 */
  180: "toExplore_var_2890",
  /** var_3973 */
  181: "toExplore_var_3973",
  /** var_4101 */
  182: "toExplore_var_4101",
  /** var_7686 */
  183: "toExplore_var_7686",
  /** var_13775 */
  184: "toExplore_var_13775",
  /** var_13058 */
  185: "toExplore_var_13058",
  /** var_4023 */
  186: "toExplore_var_4023",
  /** var_5027 */
  187: "toExplore_var_5027",
  /** var_10752 */
  500: "seqBelow",
  /** var_3887 */
  1700: "toExplore_var_3887",
  /** var_12550 */
  2000: "toExplore_var_12550",
  /** var_4033 */
  2300: "loginAcceptedAlt",
  /** var_4427 */
  2400: "toExplore_var_4427",
  /** var_1830 handler method_4458 */
  2401: "toExplore_var_1830",
  /** var_7223 handler method_6236 */
  2402: "toExplore_var_7223",
  /** var_5556 handler method_5576 */
  2403: "toExplore_var_5556",
  /** var_9615 handler method_8936 */
  2404: "toExplore_var_9615",
  /** var_10024 handler method_2704 */
  2405: "toExplore_var_10024",
  /** var_3664 handler method_8935 */
  2406: "toExplore_var_3664",
  /** var_5456 handler method_3363 */
  2407: "toExplore_var_5456",
  /** var_1230 handler method_4210 */
  2408: "toExplore_var_1230",
  /** var_9068 handler method_471 */
  2409: "toExplore_var_9068",
  /** var_6722 handler method_677 */
  2410: "toExplore_var_6722",
  /** var_1567 handler method_6922 */
  2411: "toExplore_var_1567",
  /** var_14421 handler method_7553 */
  2412: "toExplore_var_14421",
  /** var_6019 handler method_8208 */
  2413: "toExplore_var_6019",
  /** var_5026 handler method_8630 */
  2414: "toExplore_var_5026",
  /** var_13551 handler method_6157 */
  2415: "toExplore_var_13551",
  /** var_13675 handler method_3934 */
  2416: "toExplore_var_13675",
  /** var_4630 handler method_4098 */
  2417: "toExplore_var_4630",
  /** var_13749 handler method_7110 */
  2418: "toExplore_var_13749",
  /** var_6085 handler method_5796 */
  2419: "toExplore_var_6085",
  /** var_12999 handler method_7015 */
  2420: "toExplore_var_12999",
  /** var_11367 handler method_5386 */
  2421: "toExplore_var_11367",
  /** var_14724 handler method_4300 */
  2422: "toExplore_var_14724",
  /** var_6816 handler method_5974 */
  2423: "toExplore_var_6816",
  /** var_12535 handler method_7580 */
  2424: "toExplore_var_12535",
  /** var_11003 handler method_181 */
  2425: "toExplore_var_11003",
  /** var_11587 handler method_4794 */
  2426: "toExplore_var_11587",
  /** var_12296 handler method_3695 */
  2427: "toExplore_var_12296",
  /** var_7812 handler method_9023 */
  2428: "toExplore_var_7812",
  /** var_12657 handler method_7494 */
  2429: "toExplore_var_12657",
  /** var_14294 handler method_4980 */
  2430: "toExplore_var_14294",
  /** var_1783 handler method_8804 */
  2431: "loginAccepted",
  /** var_5128 handler method_189 */
  2432: "toExplore_var_5128",
  /** PKTTYPE_UNUSED_2433 */
  2433: "unused2433",
  /** var_13192 handler method_6359 */
  2434: "toExplore_var_13192",
  /** var_1544 handler method_5811 */
  2435: "toExplore_var_1544",
  /** var_8857 handler method_4705 */
  2436: "toExplore_var_8857",
  /** var_11780 handler method_222 */
  2437: "toExplore_var_11780",
  /** var_8011 handler method_3706 */
  2438: "toExplore_var_8011",
  /** var_8264 handler method_368 */
  2439: "toExplore_var_8264",
  /** var_5362 handler method_5476 */
  2440: "toExplore_var_5362",
  /** var_5622 handler method_6975 */
  2441: "toExplore_var_5622",
  /** var_3058 handler method_9039 */
  2442: "toExplore_var_3058",
  /** var_1502 handler method_5756 */
  2443: "toExplore_var_1502",
  /** var_14073 handler method_5357 */
  2444: "toExplore_var_14073",
  /** var_11345 handler method_4041 */
  2445: "customLobby",
  /** var_5230 handler method_3436 */
  2446: "toExplore_var_5230",
  /** var_5416 handler method_1168 */
  2447: "toExplore_var_5416",
  /** var_719 handler method_8238 */
  2448: "lobbySettings",
  /** var_13930 handler method_5843 */
  2449: "lobbyJoin",
  /** var_13183 handler method_8731 */
  2450: "toExplore_var_13183",
  /** var_104 handler method_4201 */
  2451: "toExplore_var_104",
  /** var_11035 */
  2452: "toExplore_var_11035",
  /** var_13632 handler method_7012 */
  2453: "toExplore_var_13632",
  /** var_9292 handler method_1572 */
  2454: "toExplore_var_9292",
  /** var_4764 handler method_6528 */
  2455: "toExplore_var_4764",
  /** var_3146 handler method_1885 */
  2456: "toExplore_var_3146",
  /** var_144 handler method_773 */
  2457: "toExplore_var_144",
  /** var_108 handler method_8634 */
  2458: "toExplore_var_108",
  /** var_4676 handler method_7618 */
  2459: "toExplore_var_4676",
  /** var_13893 handler method_5927 */
  2460: "toExplore_var_13893",
  /** var_15173 handler method_6511 */
  2461: "toExplore_var_15173",
  /** var_13367 */
  2462: "toExplore_var_13367",
  /** var_6494 handler method_6092 */
  2463: "seqExclude6494",
  /** var_6137 */
  2464: "toExplore_var_6137",
  /** var_11638 handler method_6486 */
  2465: "toExplore_var_11638",
  /** var_8382 handler method_3207 */
  2466: "assignGameServer",
  /** var_14117 */
  2467: "seqExclude14117",
  /** var_12484 handler method_8929 */
  2468: "toExplore_var_12484",
  /** var_6862 */
  2469: "toExplore_var_6862",
  /** var_13782 handler method_7487 */
  2470: "toExplore_var_13782",
  /** var_14528 handler method_4474 */
  2471: "toExplore_var_14528",
  /** var_7129 handler method_3041 */
  2472: "toExplore_var_7129",
  /** var_6447 handler method_23 */
  2473: "toExplore_var_6447",
  /** var_11965 handler method_1282 */
  2474: "toExplore_var_11965",
  /** var_12987 handler method_5639 */
  2475: "toExplore_var_12987",
  /** var_14706 handler method_2909 */
  2476: "toExplore_var_14706",
  /** var_2674 handler method_8072 */
  2477: "toExplore_var_2674",
  /** var_6093 handler method_7193 */
  2478: "toExplore_var_6093",
  /** var_7271 handler method_1298 */
  2479: "toExplore_var_7271",
  /** var_11723 handler method_5300 */
  2480: "toExplore_var_11723",
  /** var_2238 handler method_5030 */
  2481: "toExplore_var_2238",
  /** var_14284 handler method_4040 */
  2482: "toExplore_var_14284",
  /** var_10410 handler method_2555 */
  2483: "toExplore_var_10410",
  /** var_1090 handler method_5095 */
  2484: "toExplore_var_1090",
  /** var_5768 handler method_3078 */
  2485: "toExplore_var_5768",
  /** var_7330 handler method_7081 */
  2486: "toExplore_var_7330",
  /** var_4259 handler method_2137 */
  2487: "toExplore_var_4259",
  /** var_6298 handler method_8806 */
  2488: "toExplore_var_6298",
  /** var_5944 handler method_169 */
  2489: "toExplore_var_5944",
  /** var_628 handler method_2134 */
  2490: "toExplore_var_628",
  /** var_10925 handler method_8201 */
  2491: "toExplore_var_10925",
  /** var_8137 handler method_2582 */
  2492: "toExplore_var_8137",
  /** var_4000 handler method_6863 */
  2493: "toExplore_var_4000",
  /** var_12055 handler method_2602 */
  2494: "toExplore_var_12055",
  /** var_8148 handler method_7802 */
  2495: "toExplore_var_8148",
  /** var_3385 handler method_5389 */
  2496: "toExplore_var_3385",
  /** var_3048 handler method_7388 */
  2497: "toExplore_var_3048",
  /** var_9714 handler method_4424 */
  2498: "toExplore_var_9714",
  /** var_10044 handler method_6373 */
  2499: "toExplore_var_10044",
  /** var_2106 handler method_5973 */
  2500: "toExplore_var_2106",
  /** var_7332 handler method_1505 */
  2501: "toExplore_var_7332",
  /** var_10566 handler method_3688 */
  2502: "toExplore_var_10566",
  /** var_7214 handler method_5591 */
  2503: "toExplore_var_7214",
  /** var_4719 handler method_4182 */
  2504: "toExplore_var_4719",
  /** var_9992 handler method_8161 */
  2505: "toExplore_var_9992",
  /** var_6634 handler method_6235 */
  2506: "toExplore_var_6634",
  /** var_10874 handler method_6107 */
  2507: "toExplore_var_10874",
  /** var_14507 handler method_5609 */
  2508: "toExplore_var_14507",
  /** var_2752 handler var_1908.var_12876.method_6792 */
  2509: "toExplore_var_2752",
  /** var_2714 handler var_1908.var_12876.method_4132 */
  2510: "toExplore_var_2714",
  /** var_3302 handler var_1908.var_12876.method_5232 */
  2511: "toExplore_var_3302",
  /** var_2036 handler var_1908.var_12876.method_1513 */
  2512: "toExplore_var_2036",
  /** var_9139 handler var_1908.var_12876.method_9017 */
  2513: "toExplore_var_9139",
  /** var_6798 handler var_1908.var_12876.method_4846 */
  2514: "toExplore_var_6798",
  /** var_5258 handler var_1908.var_12876.method_3120 */
  2515: "toExplore_var_5258",
  /** var_197 handler var_1908.var_12876.method_8455 */
  2516: "toExplore_var_197",
  /** var_8760 handler var_1908.var_12876.method_412 */
  2517: "toExplore_var_8760",
  /** var_6950 handler var_1908.var_12876.method_9086 */
  2518: "toExplore_var_6950",
  /** var_8717 handler method_5236 */
  2519: "toExplore_var_8717",
  /** var_8771 handler method_5746 */
  2520: "toExplore_var_8771",
  /** var_4912 handler method_3705 */
  2521: "toExplore_var_4912",
  /** var_11812 handler method_737 */
  2522: "toExplore_var_11812",
  /** var_3819 handler method_1288 */
  2523: "toExplore_var_3819",
  /** var_11377 handler method_2233 */
  2524: "toExplore_var_11377",
  /** var_7624 handler method_906 */
  2525: "toExplore_var_7624",
  /** var_6617 handler method_8176 */
  2526: "toExplore_var_6617",
  /** var_2592 handler method_215 */
  2527: "toExplore_var_2592",
  /** var_9153 handler method_596 */
  2528: "toExplore_var_9153",
  /** var_14686 */
  2529: "toExplore_var_14686",
  /** var_4219 handler method_8549 */
  2530: "toExplore_var_4219",
  /** var_12369 handler method_4908 */
  2531: "toExplore_var_12369",
  /** var_8654 */
  2532: "toExplore_var_8654",
  /** var_12950 handler method_5449 */
  2533: "toExplore_var_12950",
  /** var_12142 handler method_897 */
  2534: "toExplore_var_12142",
  /** var_7879 handler method_6585 */
  2535: "toExplore_var_7879",
  /** var_3121 handler method_4603 */
  2536: "toExplore_var_3121",
  /** var_14383 handler method_7087 */
  2537: "toExplore_var_14383",
  /** var_7355 handler method_7141 */
  2538: "toExplore_var_7355",
  /** var_13755 handler method_650 */
  2539: "toExplore_var_13755",
  /** var_6198 handler method_7890 */
  2540: "toExplore_var_6198",
  /** var_13187 handler method_1561 */
  2541: "toExplore_var_13187",
  /** var_1961 handler method_4986 */
  2542: "toExplore_var_1961",
  /** var_14427 handler method_5174 */
  2543: "toExplore_var_14427",
  /** var_14840 handler method_1389 */
  2544: "toExplore_var_14840",
  /** var_9307 handler method_7629 */
  2545: "toExplore_var_9307",
  /** var_14433 handler method_637 */
  2546: "toExplore_var_14433",
  /** var_8101 handler method_6341 */
  2547: "toExplore_var_8101",
  /** var_12363 handler method_4901 */
  2548: "toExplore_var_12363",
  /** var_5406 */
  2549: "toExplore_var_5406",
  /** var_10771 handler method_8476 */
  2550: "toExplore_var_10771",
  /** var_8926 handler method_2352 */
  2551: "toExplore_var_8926",
  /** var_2649 handler method_7153 */
  2552: "toExplore_var_2649",
  /** var_806 handler var_1908.var_3800.method_7582 */
  2700: "toExplore_var_806",
  /** var_10553 */
  2701: "toExplore_var_10553",
  /** var_14859 handler method_2139 */
  2702: "toExplore_var_14859",
  /** var_4156 */
  2703: "toExplore_var_4156",
  /** var_7859 handler var_1908.var_15268.method_335 */
  2750: "toExplore_var_7859",
  /** var_13332 handler var_1908.var_15268.method_8704 */
  2751: "toExplore_var_13332",
  /** var_6657 handler var_1908.var_15268.method_3426 */
  2752: "toExplore_var_6657",
  /** var_13800 handler var_1908.var_15268.method_109 */
  2753: "toExplore_var_13800",
  /** var_8301 handler var_1908.var_15268.method_6494 */
  2754: "toExplore_var_8301",
  /** var_9958 handler var_1908.var_15268.method_1943 */
  2755: "toExplore_var_9958",
  /** var_14991 handler method_4043 */
  2760: "toExplore_var_14991",
  /** var_13328 handler method_6592 */
  2800: "toExplore_var_13328",
  /** var_9591 */
  2801: "toExplore_var_9591",
  /** var_13070 handler method_3323 */
  2802: "toExplore_var_13070",
  /** var_11451 handler var_1908.var_11994.method_5116 */
  2803: "toExplore_var_11451",
  /** var_10267 handler var_1908.var_11994.method_5374 */
  2804: "toExplore_var_10267",
  /** var_11878 handler var_1908.var_11994.method_1332 */
  2805: "toExplore_var_11878",
  /** var_675 handler method_2468 */
  2850: "toExplore_var_675",
  /** var_10800 handler method_7775 */
  2851: "toExplore_var_10800",
  /** var_14631 handler method_6323 */
  2852: "toExplore_var_14631",
  /** var_2573 handler method_5825 */
  2853: "toExplore_var_2573",
  /** var_3019 handler method_1032 */
  2854: "toExplore_var_3019",
  /** var_14098 handler method_7953 */
  2900: "toExplore_var_14098",
  /** var_15166 handler method_7673 */
  2901: "toExplore_var_15166",
  /** var_14817 handler var_1908.var_8299.method_6629 */
  2902: "toExplore_var_14817",
  /** var_1695 handler method_7435 */
  2903: "toExplore_var_1695",
  /** var_7922 */
  2904: "toExplore_var_7922",
  /** var_13453 */
  2905: "toExplore_var_13453",
  /** var_7480 handler method_1875 */
  2906: "toExplore_var_7480",
  /** var_4480 handler method_1498 */
  2907: "toExplore_var_4480",
  /** var_14304 handler method_3181 */
  2908: "toExplore_var_14304",
  /** var_2586 handler method_531 */
  2909: "toExplore_var_2586",
  /** var_700 handler method_6684 */
  2910: "toExplore_var_700",
  /** var_15093 handler var_1908.var_8299.method_7704 */
  2911: "toExplore_var_15093",
  /** var_11154 handler method_329 */
  2912: "toExplore_var_11154",
  /** var_493 handler method_212 */
  2913: "toExplore_var_493",
  /** var_4249 handler var_1908.var_11994.method_7232 */
  2914: "toExplore_var_4249",
  /** var_8563 handler method_3438 */
  2915: "toExplore_var_8563",
  /** var_15051 handler method_4942 */
  2916: "toExplore_var_15051",
  /** var_9891 handler var_1908.var_15268.method_7043 */
  2917: "toExplore_var_9891",
  /** var_12978 handler method_4655 */
  2918: "toExplore_var_12978",
  /** var_3750 handler method_5062 */
  2919: "toExplore_var_3750",
  /** var_11689 handler var_1908.var_7783.method_8818 */
  2920: "toExplore_var_11689",
  /** var_4706 handler var_1908.var_13599.method_270 */
  2921: "toExplore_var_4706",
  /** var_14343 handler var_1908.var_13599.method_7135 */
  2922: "toExplore_var_14343",
  /** var_3355 handler var_1908.var_13599.method_6611 */
  2923: "toExplore_var_3355",
  /** var_1315 handler var_1908.var_13599.method_370 */
  2924: "toExplore_var_1315",
  /** var_13844 handler var_1908.var_8299.method_1950 */
  2925: "toExplore_var_13844",
  /** var_1642 handler method_8943 */
  2926: "toExplore_var_1642",
  /** var_3186 handler var_1908.var_8299.method_2303 */
  2927: "toExplore_var_3186",
  /** var_8718 */
  3000: "toExplore_var_8718",
  /** var_12278 handler method_233 */
  10100: "toExplore_var_12278",
  /** var_10802 handler method_1323 */
  10101: "toExplore_var_10802",
  /** var_11627 handler method_8900 */
  10102: "toExplore_var_11627",
  /** var_5978 handler method_55 */
  10103: "toExplore_var_5978",
  /** var_8173 handler method_7426 */
  10104: "toExplore_var_8173",
  /** var_7067 handler method_6299 */
  10105: "toExplore_var_7067",
  /** var_15232 handler method_2962 */
  10106: "toExplore_var_15232",
  /** var_2249 handler method_2816 */
  10107: "toExplore_var_2249",
  /** var_13299 */
  10200: "toExplore_var_13299",
  /** var_7890 */
  10201: "toExplore_var_7890",
  /** var_13445 */
  10202: "toExplore_var_13445",
  /** var_3514 handler method_6725 — method_6725 Error_FAILED_TRANSFER */
  10300: "transferFailed",
  /** var_8486 handler method_6892 — method_6892 tick pulse */
  10301: "tickPulse",
  /** var_14908 PKTTYPE_ENT_RECONNECTED handler method_4515 — ReadReconnectedEntity */
  10302: "entReconnected",
  /** var_11924 PKTTYPE_ENT_DISCONNECTED handler method_1337 — ReadDisconnectedEntity */
  10303: "entDisconnected",
  /** var_8091 handler method_3520 — method_3520 stock/entity state */
  10304: "entityState",
  /** var_11598 handler method_7070 */
  10305: "inputHistory",
  /** var_2471 handler method_3721 */
  10306: "matchEnd",
  /** var_8260 handler method_2473 */
  10307: "entityRespawn",
  /** var_12769 handler method_3964 */
  10308: "entityRollback",
  /** var_6185 handler method_2963 — method_2963 rollback inputs */
  10309: "inputBroadcast",
  /** var_5141 handler method_8497 — method_8497 match setup */
  10310: "matchSetup",
  /** var_3 handler method_8604 — method_8604 session sync */
  10311: "sessionSync",
  /** var_7923 handler method_288 — method_288 entity spawn loop */
  10312: "entitySpawn",
  /** var_3324 PKTTYPE_GAMESERVER_READY handler method_4724 — ReadGameServerReady */
  10313: "gameserverReady",
  /** var_10734 handler method_7952 */
  10314: "canQuitNoPenalty",
  /** var_1712 handler method_3926 */
  10315: "entityPoke",
  /** var_5078 handler method_8562 — method_8562 UDP tunnel */
  10316: "udpTunnel",
  /** var_9886 PKTTYPE_GAMESERVER_LOGIN */
  10400: "gameserverLogin",
  /** var_14245 PKTTYPE_ENT_READY_TO_START — WriteReadyToStartPacket quit/forfeit */
  10401: "entReadyToStart",
  /** var_11986 */
  10402: "toExplore_var_11986",
  /** var_8410 PKTTYPE_RESYNCH_READY */
  10403: "resynchReady",
  /** var_7095 handler method_2517 — method_2517 tick ack */
  10404: "tickAck",
  /** var_3975 PKTTYPE_GAMESERVER_LOGIN_REJOIN */
  10405: "gameserverLoginRejoin",
  /** var_14768 */
  10406: "toExplore_var_14768",
  /** var_5618 */
  10407: "moveInput",
  /** var_6405 handler method_4510 */
  10408: "toExplore_var_6405",
  /** var_174 */
  10409: "levelReady",
  /** var_13980 */
  10410: "toExplore_var_13980",
  /** var_7112 */
  10411: "toExplore_var_7112",
  /** var_3334 */
  10412: "toExplore_var_3334",
  /** var_4430 */
  10413: "toExplore_var_4430",
  /** var_8692 */
  10414: "toExplore_var_8692",
  /** var_12127 */
  10415: "introPlayerSync",
  /** var_8209 */
  10416: "toExplore_var_8209",
  /** var_14045 */
  10417: "toExplore_var_14045",
  /** var_6123 */
  10418: "toExplore_var_6123",
  /** var_4272 */
  10419: "introEntitySync",
  /** var_5138 */
  10420: "toExplore_var_5138",
  /** var_7743 */
  10421: "toExplore_var_7743",
  /** var_6928 */
  10422: "introAuxSync",
  /** var_1854 */
  10423: "toExplore_var_1854",
  /** var_7394 handler method_6536 */
  12000: "loginChallenge",
  /** var_7469 handler method_2886 */
  12001: "authRefused",
  /** var_4304 PKTTYPE_EXIT_GAMESERVER handler method_7929 — method_7929 exit to offline/main menu */
  12002: "exitGameserver",
  /** var_6203 handler class_60.method_2128 */
  12003: "toExplore_var_6203",
  /** var_14380 handler method_3632 */
  12100: "keepalivePing",
} as const satisfies Record<number, string>;

export type PacketAlias = (typeof aliasesByType)[keyof typeof aliasesByType];
